name: "weather-bot"

on:
  push:
  schedule:
    - cron: "0 6 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install dependencies"
        run: npm install
      - name: "Run code"
        run: node index.js
        env:
          OPEN_WEATHER_MAP_TOKEN: ${{ secrets.OPEN_WEATHER_MAP_TOKEN }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_BOT_CHAT_ID: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}
          TELEGRAM_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_GROUP_CHAT_ID }}
